apache/teaclave-trustzone-sdk

- optee-teec/optee-teec-sys/src/tee_client_api.rs
- optee-utee/optee-utee-sys/src/tee_api.rs
- optee-utee/optee-utee-sys/src/tee_api_types.rs
- optee-utee/optee-utee-sys/src/utee_syscalls.rs
- optee-utee/systest/src/main.rs
Removed all 'libc::\*int\*_t' in code.
> Remove all other deprecated fixed width int libc variables.

- examples/aes/ta/src/main.rs
- optee-utee/optee-utee-sys/src/tee_api.rs
- optee-utee/src/crypto_op.rs
Hi @mssun 
A new API was defined in OPTEE 3.9.0+ which is `TEE_IsAlgorithmSupported`.
So I've updated:
1. function wrapper `is_algorithm_supported` for `TEE_IsAlgorithmSupported`
2. examples/aes/ta to test `is_algorithm_supported`
Best Regards,
Yuan
> add support for new TEE API and update examples/aes/ta

- .cargo/config
- .github/workflows/ci.yml
- Makefile
- README.md
- environment
- .cargo/config: remove relative path of toolchains since it has been added to `PATH` in `source environment`
- Makefile: add installation of plugins in example-install
- Makefile, environment and README.md: `OPTEE_DIR` allows setting OPTEE root path
- .github/workflows/ci.yml: fix related ci error
> Update makefile and environment variables

- environment
- optee-teec/optee-teec-sys/build.rs
[OP-TEE remove optee_client static library target](https://github.com/OP-TEE/build/commit/819066fb88a65b5e8c572ede5a50ebe5f29f5b25).
> change optee-teec to use dynamic optee_client library and add setup.sh

- docs/README.md
- docs/overview-of-optee-rust-examples.md
Add `overview-of-optee-rust-examples.md` in `docs/`.
> Add documentation of Rust examples

- environment
If `OPTEE_DIR` set by user, toolchains should be there too.
> correct toolchain PATH env

- .github/workflows/ci.yml
- ci/qemu-check.exp
Add `ci/qemu-check.exp` which invoked in OP-TEE/build/qemu_v8.mk
First, build Rust applications in buildroot:
```
$ (cd build && make toolchains && make OPTEE_RUST_ENABLE=y CFG_TEE_RAM_VA_SIZE=0x00300000)
```
Then trigger the CI for Rust applications in OP-TEE by:
```
$ (cd build && make CFG_TEE_CORE_LOG_LEVEL=0 check-rust)
```
> Add expect script for OP-TEE CI

- .github/workflows/ci.yml
"make check-rust" will build images and Rust examples then run tests.
Remove the redundant "make" and add "-j" to reduce ci time.
> ci.yml: remove redundant building process

- tests/test_acipher.sh
- tests/test_aes.sh
- tests/test_authentication.sh
- tests/test_big_int.sh
- tests/test_diffie_hellman.sh
- tests/test_digest.sh
- tests/test_hello_world.sh
- tests/test_hotp.sh
- tests/test_message_passing_interface.sh
- tests/test_random.sh
- tests/test_secure_storage.sh
- tests/test_serde.sh
- tests/test_signature_verification.sh
- tests/test_supp_plugin.sh
- tests/test_tcp_client.sh
- tests/test_time.sh
- tests/test_udp_socket.sh
Use [Apache Nightlies](https://nightlies.apache.org/authoring.html) for storing CI assets.
Directory: https://nightlies.apache.org/teaclave/teaclave-trustzone-sdk/
> ci: update the link for assets

- examples/authentication-rs/host/src/main.rs
The nonce defined in examples/authentication-rs/host/src/main.rs has a size of 2 octets. It turns out that this value is invalid as per RFC 3610 section 2 [1]:
"Valid values of L range between 2 octets and 8 octets (the value L=1
is reserved)."
"A nonce N of 15-L octets"
The two statements above imply than the nonce can only be between 7 and 13 octets.
The AES CCM implementation in LibTomCrypt has recently added stricter validation of the nonce size [2]. As soon as OP-TEE upgrades, the authentication-rs example will fail as follows:
```
Error: Trusted Application has panicked during the operation. (error code 0xffff3024)
(Secure console -- call stack processed by optee_os/scripts/symbolize.py)
[+] TA create
[+] TA open session
[+] TA invoke command
[+] TA prepare
E/TC:? 0
E/TC:? 0 TA …
```
> authentication-rs: set nonce size to 8 bytes

- .github/workflows/ci.yml
- setup.sh
- Bump rust toolchain version for fixing cargo error: `error[E0658]: use of unstable library feature 'str_strip': newly added`.
- fix ci error: `>>> optee_test_ext 1.0 Building.. make[2]:execvp: /bin/bash: Argument list too long`
> Fix cargo error

- optee-teec/optee-teec-sys/Cargo.toml
- optee-utee/optee-utee-sys/Cargo.toml
This lets dependents with their own way of linking to libteec and/or libutee override our build script if they so choose. See the documentation [here](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts).
This contribution is on behalf of my company.
> Add "links" field to Cargo.toml for teec and utee

- optee-teec/optee-teec-sys/src/tee_client_api.rs
- optee-teec/src/context.rs
We've been updating our OP-TEE version without updating our Rust definitions of its API types. Since the GlobalPlatform TEE Client API uses client-allocated API objects, our code needs to be aware of and match the implementation-specific fields used by the version of libteec we link to.
This pulls in two changes that we missed, one of which increases the space we need to allocate for TEEC_Context and so results in memory unsafety with our current definitions:
- OP-TEE/optee_client#145
- OP-TEE/optee_client#217
> optee-teec: update OP-TEE implementation fields

- examples/acipher-rs/ta/build.rs
- examples/aes-rs/ta/build.rs
- examples/authentication-rs/ta/build.rs
- examples/big_int-rs/ta/build.rs
- examples/diffie_hellman-rs/ta/build.rs
- examples/digest-rs/ta/build.rs
- examples/hello_world-rs/ta/build.rs
- examples/hotp-rs/ta/build.rs
- examples/random-rs/ta/build.rs
- examples/secure_storage-rs/ta/build.rs
- examples/signature_verification-rs/ta/build.rs
- examples/supp_plugin-rs/ta/build.rs
- examples/time-rs/ta/build.rs
Refactor TAs build script code to reuse 64K section alignment hook for 32-bit TAs. This would allow linker to separate executable code from writable data and in turn fix following runtime abort with 32-bit TAs:
E/TC:? 0
E/TC:? 0 User mode prefetch-abort at address 0x400410e4 (read permission fault)
E/TC:? 0  esr 0x8200000f  ttbr0 0x200000e1b2020   ttbr1 0x00000000   cidr 0x0
E/TC:? 0  cpu #1          cpsr 0x00000110
E/TC:? 0  x0  0000000000000000 x1  000000000009e850
E/TC:? 0  x2  0000000040015f80 x3  0000000000000000
E/TC:? 0  x4  0000000000000000 x5  0000000000000000
E/TC:? 0  x6  0000000000000000 x7  0000000000000000
E/TC:? 0  x8  0000000000000000 x9  0000000000000000
E/TC:? 0  x10 0000000000000000 x11 0000000000000000
E/TC:? 0  x12 0000000000000000 x13 0000000040015f80
E/TC:? 0  x14 …
> examples: 32-bit TAs: Fix runtime abort

- .github/workflows/ci.yml
Now OP-TEE build system has been updated to support 32-bit Rust TAs, so enable runtime testing for them.
> CI: Enable 32-bit Rust examples runtime testing

- examples/acipher-rs/host/Makefile
- examples/acipher-rs/ta/Makefile
- examples/aes-rs/host/Makefile
- examples/aes-rs/ta/Makefile
- examples/authentication-rs/host/Makefile
- examples/authentication-rs/ta/Makefile
- examples/big_int-rs/host/Makefile
- examples/big_int-rs/ta/Makefile
- examples/diffie_hellman-rs/host/Makefile
- examples/diffie_hellman-rs/ta/Makefile
- examples/digest-rs/host/Makefile
- examples/digest-rs/ta/Makefile
- examples/hello_world-rs/host/Makefile
- examples/hello_world-rs/ta/Makefile
- examples/hotp-rs/host/Makefile
- examples/hotp-rs/ta/Makefile
- examples/random-rs/host/Makefile
- examples/random-rs/ta/Makefile
- examples/secure_storage-rs/host/Makefile
- examples/secure_storage-rs/ta/Makefile
- examples/signature_verification-rs/host/Makefile
- examples/signature_verification-rs/ta/Makefile
- examples/supp_plugin-rs/host/Makefile
- examples/supp_plugin-rs/ta/Makefile
- examples/time-rs/host/Makefile
- examples/time-rs/ta/Makefile
The Makefiles for the examples lacked dependencies between rules, resulting in some cases resulted in build error. To maintain a coherent build process, this commit introduces dependencies to ensure that binaries are built before being stripped and signed.
> examples: ensure the proper build order

- optee-utee/src/crypto_op.rs
- optee-utee/src/object.rs
optee-utee is missing a few algorithm and attribute identifiers required for implementing AOSP KeyMint TA [1].  Add the missing RSA and ECC constants.
[1] https://android.googlesource.com/platform/system/keymint/
> Add missing identifiers for RSA and elliptic curves

- .github/workflows/ci.yml
- Dockerfile
- ci/ci.sh
- environment
- setup.sh
- tests/cleanup_all.sh
- tests/setup.sh
- tests/test_acipher.sh
- tests/test_aes.sh
- tests/test_authentication.sh
- tests/test_big_int.sh
- tests/test_diffie_hellman.sh
- tests/test_digest.sh
- tests/test_hello_world.sh
- tests/test_hotp.sh
- tests/test_message_passing_interface.sh
- tests/test_random.sh
- tests/test_secure_storage.sh
- tests/test_serde.sh
- tests/test_signature_verification.sh
- tests/test_supp_plugin.sh
- tests/test_tcp_client.sh
- tests/test_time.sh
- tests/test_tls_client.sh
- tests/test_tls_server.sh
- tests/test_udp_socket.sh
- update to OP-TEE 4.2.0
- simplify test scripts
- use new docker img based on Ubuntu 24.04 (required by qemu libslirp)
> Update to OP-TEE 4.2.0

- ci/ci.sh
- ci/qemu-check.exp
- examples/error_handling-rs/host/src/main.rs
- tests/cleanup_all.sh
- tests/optee-qemuv8.sh
- tests/setup.sh
- tests/test_acipher.sh
- tests/test_aes.sh
- tests/test_authentication.sh
- tests/test_big_int.sh
- tests/test_diffie_hellman.sh
- tests/test_digest.sh
- tests/test_error_handling.sh
- tests/test_hotp.sh
- tests/test_random.sh
- tests/test_secure_storage.sh
- tests/test_signature_verification.sh
- tests/test_supp_plugin.sh
- tests/test_time.sh
- Use the OP-TEE 4.2.0 prebuilt images and avoid multiple downloads;
- Add `tests/setup.sh` for common operations;
- Add `error_handling` test in qemu ci;
- unify scripts' indentation.
Similar changes on master branch: [1].
[1] https://github.com/apache/incubator-teaclave-trustzone-sdk/commit/b05173f3ad3274b361b089896d0f51aa74ee6dd4
> [no-std] Simplify test scripts

- examples/acipher-rs/host/src/main.rs
* Subtract 1 from args.len() to get the number of arguments (arg[0] is program path/name)
* Improve the "Correct usage" string to show a (more) standard synopsis
* Improve the message when key size < 256 is specified.
Signed-off-by: Sean Gilligan <sean@msgilligan.com>
> acipher main.rs: Fix arg validation error messages

- optee-utee/src/object.rs
Add a new function `is_null_object` to `TransientObject`, it checks if the underlying `ObjectHandle` was created from null pointer.
The possible use case is do safey check before read or write.
> optee-utee: Add a new function is_null_object to TransientObject

- optee-utee/Cargo.toml
- optee-utee/src/lib.rs
Make panic_handler optional for no-std TAs by adding "no_panic_handler" feature flag. It allows no-std TAs to have a custom panic handler.
Relative issue is here: #145 
This PR is a recreate one, the former PR was closed due to using the wrong branch(as metioned in #143 , the only maintenance branch should be main.
> no-std: optee-utee: make panic_handler optional

- optee-utee/Cargo.toml
Unlock the version of bitflags in optee-utee to avoid confliction when using optee-utee with some other crates(like cpuid).
This PR relate to issue #148
> optee-utee: do not lock the version of bitflags crate

- .github/workflows/ci.yml
- optee-teec/optee-teec-sys/build.rs
- optee-teec/src/uuid.rs
- optee-utee/optee-utee-sys/build.rs
- optee-utee/src/uuid.rs
1) change the realization of Display trait of Uuid, make its formation
const of 36 bytes.
2) introduce an env(RUN_TEST_IN_REE) in optee-utee-sys crate so that
we can run library tests of optee-utee
This one relates to #151
> Change the output formation of ToString method of Uuid

- optee-utee/Cargo.toml
- optee-utee/src/extension.rs
- optee-utee/systest/Cargo.toml
1) introduce a Command struct for flexible use
2) allow developers settings capacity of shared buffer when invoking
command
> optee-utee: support setting capacity of shared buffer of LoadablePlugin

- README.md
This PR aims to update the outdated information about the Rust version of `STD` in the README.
> Doc: update rust information of STD

- setup.sh
`cargo --version` is used to trigger the Rust toolchain installation but does not work currently and fails with the error: 
"error: toolchain 'nightly-....'is not installed"
Use the `rustup toolchain install` instead.
> setup: fix toolchain installation error

- examples/supp_plugin-rs/host/src/main.rs
- examples/supp_plugin-rs/plugin/Cargo.toml
- examples/supp_plugin-rs/plugin/build.rs
- examples/supp_plugin-rs/plugin/plugin_static.rs
- examples/supp_plugin-rs/plugin/src/lib.rs
- examples/supp_plugin-rs/proto/src/lib.rs
- examples/supp_plugin-rs/ta/build.rs
- examples/supp_plugin-rs/ta/src/main.rs
- optee-teec/macros/Cargo.toml
- optee-teec/macros/src/lib.rs
- optee-teec/src/context.rs
- optee-teec/src/error.rs
- optee-teec/src/extension.rs
- optee-teec/src/lib.rs
- optee-teec/src/operation.rs
- optee-teec/src/parameter.rs
- optee-teec/src/session.rs
- optee-teec/src/uuid.rs
1. Fix usage of Rust types as return values in FFI functions.
https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/cf0f662eec9213be32bf972888f422575b03bc7a/optee-teec/src/extension.rs#L23-L33
Currently, the plugin's methods use Rust's `optee_teec::Result` as the return value for `FFI`, which is incorrect since Rust does not guarantee a stable ABI. We need to change them to `optee_teec_sys::TEEC_Result`(alias of u32) instead.
2. Standardize the function signature to require returning a Result.
Similar to the original signatures of TEEC functions, we currently require the plugin's methods to return an error.
* For `init`: from `fn()` to `fn() -> optee_teec::Result<()>`
* For `invoke_command`: from `fn(&mut optee_teec::PluginParameters)` to `fn(&mut optee_teec::PluginParameters) …
> optee_teec: extension: fix macro errors

- .github/workflows/build_runner_image.yml
Support building runner images for both arm64 and amd64 via github ci.
This PR will allow developers to build a runner image through github actions.
After the pipeline success, the runner image can be found under the developers' packages.
Currently we build container with two platforms: `linux/amd64`, `linux/arm64`.
> ci: add build_runner_image.yml

- optee-teec/src/uuid.rs
- optee-utee/src/uuid.rs
Compare wrapped results instead of using `unwrap()`
> Remove unwrap in test case

- optee-teec/src/context.rs
- optee-teec/src/session.rs
Adding a new method to open a session with login field set by caller instead of hard coding it to default (`ConnectionMethods::LoginPublic`)
Legacy constructor is not removed.
> Expose login field from raw::TEEC_OpenSession

- build_optee_libraries.sh
- optee-teec/Cargo.toml
- optee-teec/macros/Cargo.toml
- optee-teec/optee-teec-sys/Cargo.toml
- optee-teec/systest/Cargo.toml
- optee-utee-build/Cargo.toml
- optee-utee/Cargo.toml
- optee-utee/macros/Cargo.toml
- optee-utee/optee-utee-sys/Cargo.toml
- optee-utee/systest/Cargo.toml
- Bump OP-TEE version to `4.6.0`
- Bump optee-* crates version to `0.5.0`
> Version bump for release 0.5.0

- optee-utee/src/object.rs
Add method to access objectType of TEE_ObjectInfo.
> optee-utee: expose objectType from TEE_ObjectInfo

- .github/workflows/reuse_test_in_optee_repo.yml
- Remove unused packages from the host machine, freeing approximately 15 GB of disk space.
- Build directly on the host machine instead of using a container. Seems the container only installed OP-TEE dependencies https://github.com/apache/incubator-teaclave-trustzone-sdk/blob/main/Dockerfile, which can now be handled directly on the host. Running everything on the host avoids unnecessary switching between host and container environments.
Since the CI is not triggered for PRs, you can see it passed on my fork: https://github.com/DemesneGH/rust-optee-trustzone-sdk
> ci: cleanup unused packages for OP-TEE workflows

- Dockerfile.dev
- docs/release-tips.md
- scripts/release/build_dev_docker.sh
- scripts/release/make_release_artifacts.sh
- scripts/setup/bootstrap_env
- past `OPTEE_VERSION` when building dev docker, add the `build_dev_docker.sh` to simplify building for each OP-TEE release version
- update mail template to use the dev docker for source build testing
- fix top dir name for release artifacts
- remove completed Release 0.6.0 from the upcoming release plan
> scripts: update for release process

- Makefile
- examples/Makefile
The CI for building in OP-TEE repo fails:
```
/bin/sh: 1: clippy: not found
```
This happens because the OP-TEE build system does not `source environment` to set up environment variables; it passes parameters from the caller and does not specify the BUILDER:
https://github.com/OP-TEE/build/blob/master/br-ext/package/optee_rust_examples_ext/optee_rust_examples_ext.mk
The BUILDER and FEATURES should have default values in root Makefile, ensuring compatibility with this case. 
Also added in examples/Makefile.
> build: fix building error in OP-TEE repo

- .github/workflows/reuse_test.yml
- optee-teec/macros/src/lib.rs
- optee-teec/optee-teec-sys/src/tee_client_api.rs
- optee-teec/src/extension.rs
- optee-teec/src/operation.rs
- optee-teec/src/parameter.rs
- optee-utee/macros/src/lib.rs
- optee-utee/optee-utee-sys/src/user_ta_header.rs
- optee-utee/src/arithmetical.rs
- optee-utee/src/crypto_op.rs
- optee-utee/src/error.rs
- optee-utee/src/extension.rs
- optee-utee/src/net/optee.rs
- optee-utee/src/object/attribute.rs
- optee-utee/src/object/object_define.rs
- optee-utee/src/object/object_info.rs
- optee-utee/src/object/persistent_object.rs
- optee-utee/src/object/transient_object.rs
- optee-utee/src/parameter.rs
- optee-utee/src/property.rs
- optee-utee/src/tee_parameter.rs
- optee-utee/src/time.rs
This PR enables default Clippy and Rust compiler checks `cargo clippy -- -D warnings` for `optee-utee` and `optee-teec` in our CI.
It also fixes Clippy-reported issues, including `match-like-matches-macro`, `needless-borrowed-reference`, `not-unsafe-ptr-arg-deref`, `needless_return`, `unnecessary_cast`, and so on.
Some `#[allow(...)]` attributes are retained:
- `#[allow(non_camel_case_types)]` in `optee-*-sys`, which defines raw C structures.
- `#[allow(non_snake_case)]` in `optee-utee-mock`.
-------
- [DONE] All examples: enable default Clippy + compiler checks ([https://github.com/apache/teaclave-trustzone-sdk/pull/224](https://github.com/apache/teaclave-trustzone-sdk/pull/224)).
- [DONE] All examples: enable advanced panic checks …
> optee-*: clippy default enforcement in CI
